// ignore_for_file: constant_identifier_names

class PurposeOption {
  final String id;
  final String emoji;
  final String label;
  final String subtitle;
  const PurposeOption({required this.id, required this.emoji, required this.label, required this.subtitle});
}

class InterestItem {
  final String id;
  final String label;
  const InterestItem({required this.id, required this.label});
}

class InterestCategory {
  final String id;
  final String title;
  final String emoji;
  final List<InterestItem> interests;
  const InterestCategory({required this.id, required this.title, required this.emoji, required this.interests});
}

const List<PurposeOption> PURPOSE_OPTIONS = [
  PurposeOption(id: 'learn_language',          emoji: '🌐', label: 'Learn a new language',           subtitle: 'Practice and improve language skills globally'),
  PurposeOption(id: 'improve_communication',   emoji: '🗣️', label: 'Improve communication skills',   subtitle: 'Build confidence and fluency in real conversations'),
  PurposeOption(id: 'find_startup_teammates',  emoji: '🚀', label: 'Find startup teammates',          subtitle: 'Connect with builders and future co-founders'),
  PurposeOption(id: 'find_a_friend',           emoji: '🤗', label: 'Find a friend',                   subtitle: 'Make new meaningful friendships'),
  PurposeOption(id: 'professional_networking', emoji: '💼', label: 'Professional networking',         subtitle: 'Career connections and opportunities'),
  PurposeOption(id: 'activity_partners',       emoji: '⚽', label: 'Activity/hobby partners',         subtitle: 'Sports, gym, music, etc.'),
];

const List<InterestCategory> INTEREST_CATEGORIES = [
  InterestCategory(id: 'hobbies_creative', title: 'Hobbies & Creative', emoji: '🎨', interests: [
    InterestItem(id: 'video_gaming',      label: 'Video gaming'),
    InterestItem(id: 'reading',           label: 'Reading (#BookTok)'),
    InterestItem(id: 'drawing_art',       label: 'Drawing/Art'),
    InterestItem(id: 'cooking_baking',    label: 'Cooking/Baking'),
    InterestItem(id: 'listening_music',   label: 'Listening to music'),
    InterestItem(id: 'photography',       label: 'Photography'),
    InterestItem(id: 'film_photography',  label: 'Film/Analog photography'),
    InterestItem(id: 'board_games',       label: 'Board games'),
    InterestItem(id: 'crafting',          label: 'Crafting/DIY'),
    InterestItem(id: 'gardening',         label: 'Gardening/Urban homesteading'),
    InterestItem(id: 'ceramics_pottery',  label: 'Ceramics/Pottery'),
    InterestItem(id: 'crochet_knitting',  label: 'Crochet/Knitting'),
    InterestItem(id: 'embroidery',        label: 'Embroidery/Cross-stitch'),
    InterestItem(id: 'journaling',        label: 'Journaling'),
    InterestItem(id: 'junk_journaling',   label: 'Junk journaling'),
    InterestItem(id: 'candle_making',     label: 'Candle-making'),
    InterestItem(id: 'vinyl_collecting',  label: 'Vinyl record collecting'),
    InterestItem(id: 'calligraphy',       label: 'Calligraphy'),
    InterestItem(id: 'woodworking',       label: 'Woodworking'),
    InterestItem(id: 'sewing',            label: 'Sewing'),
    InterestItem(id: 'origami',           label: 'Origami'),
    InterestItem(id: 'lego',              label: 'LEGO building'),
    InterestItem(id: 'puzzles',           label: 'Puzzles'),
    InterestItem(id: 'fermentation',      label: 'Fermentation (sourdough, kimchi, kombucha)'),
    InterestItem(id: 'mushroom_foraging', label: 'Mushroom foraging'),
    InterestItem(id: 'birdwatching',      label: 'Birdwatching'),
  ]),
  InterestCategory(id: 'entertainment_media', title: 'Entertainment & Media', emoji: '🎬', interests: [
    InterestItem(id: 'streaming',         label: 'Streaming (Netflix, Hulu, Disney+)'),
    InterestItem(id: 'youtube',           label: 'YouTube'),
    InterestItem(id: 'tiktok',            label: 'TikTok'),
    InterestItem(id: 'short_form_video',  label: 'Short-form video content'),
    InterestItem(id: 'podcasts',          label: 'Podcasts'),
    InterestItem(id: 'anime',             label: 'Anime'),
    InterestItem(id: 'manga',             label: 'Manga/Webtoons'),
    InterestItem(id: 'kpop_kdrama',       label: 'K-pop/K-drama'),
    InterestItem(id: 'cdrama',            label: 'C-drama/J-drama'),
    InterestItem(id: 'microdramas',       label: 'Microdramas'),
    InterestItem(id: 'comedy_memes',      label: 'Comedy/Memes'),
    InterestItem(id: 'true_crime',        label: 'True crime'),
    InterestItem(id: 'reality_tv',        label: 'Reality TV'),
    InterestItem(id: 'live_streaming',    label: 'Live streaming'),
    InterestItem(id: 'documentaries',     label: 'Documentaries'),
    InterestItem(id: 'fan_fiction',       label: 'Fan fiction/Fandoms'),
    InterestItem(id: 'movie_nights',      label: 'Movie nights'),
    InterestItem(id: 'tabletop_rpg',      label: 'Tabletop RPG (D&D, etc.)'),
  ]),
  InterestCategory(id: 'music_genres', title: 'Music Genres', emoji: '🎵', interests: [
    InterestItem(id: 'hiphop',             label: 'Hip-hop'),
    InterestItem(id: 'rap',                label: 'Rap'),
    InterestItem(id: 'pop',                label: 'Pop'),
    InterestItem(id: 'indie_alternative',  label: 'Indie/Alternative'),
    InterestItem(id: 'kpop_music',         label: 'K-pop'),
    InterestItem(id: 'rnb',                label: 'R&B/Soul'),
    InterestItem(id: 'electronic',         label: 'Electronic/EDM'),
    InterestItem(id: 'phonk_fonk',         label: 'Phonk/Drift'),
    InterestItem(id: 'afrobeats',          label: 'Afrobeats/Afropop'),
    InterestItem(id: 'latin_music',        label: 'Latin (Reggaeton, Corridos, etc.)'),
    InterestItem(id: 'pop_punk',           label: 'Pop punk/Emo revival'),
    InterestItem(id: 'metal',              label: 'Metal/Metalcore'),
    InterestItem(id: 'jazz',               label: 'Jazz/Neo-soul'),
    InterestItem(id: 'classical',          label: 'Classical/Orchestral'),
    InterestItem(id: 'country',            label: 'Country/Folk'),
    InterestItem(id: 'lo_fi',              label: 'Lo-fi/Chill beats'),
    InterestItem(id: 'music_production',   label: 'Music production/Beatmaking'),
    InterestItem(id: 'playing_instruments',label: 'Playing instruments'),
  ]),
  InterestCategory(id: 'technology', title: 'Technology', emoji: '💻', interests: [
    InterestItem(id: 'gaming_tech',     label: 'Gaming (mobile, console, PC)'),
    InterestItem(id: 'ar_vr',          label: 'AR/VR/XR experiences'),
    InterestItem(id: 'coding',         label: 'Coding/App development'),
    InterestItem(id: 'vibe_coding',    label: 'Vibe coding (AI-assisted building)'),
    InterestItem(id: 'ai_tools',       label: 'AI tools & prompting'),
    InterestItem(id: 'content_creation',label: 'Content creation'),
    InterestItem(id: 'fintech_apps',   label: 'Fintech apps'),
    InterestItem(id: 'startup',        label: 'Startups'),
    InterestItem(id: 'robotics',       label: 'Robotics/Automation'),
    InterestItem(id: 'cybersecurity',  label: 'Cybersecurity'),
    InterestItem(id: 'web3',           label: 'Web3/Blockchain'),
    InterestItem(id: 'open_source',    label: 'Open source'),
    InterestItem(id: 'gadgets',        label: 'Gadgets & tech gear'),
    InterestItem(id: 'space_tech',     label: 'Space tech'),
    InterestItem(id: 'no_code',        label: 'No-code/Low-code tools'),
  ]),
  InterestCategory(id: 'sports_fitness', title: 'Sports & Fitness', emoji: '🏋️', interests: [
    InterestItem(id: 'gym',              label: 'Gym workouts'),
    InterestItem(id: 'reformer_pilates', label: 'Reformer Pilates'),
    InterestItem(id: 'yoga',             label: 'Yoga'),
    InterestItem(id: 'meditation',       label: 'Meditation/Mindfulness'),
    InterestItem(id: 'running_clubs',    label: 'Running/Social run clubs'),
    InterestItem(id: 'cycling',          label: 'Cycling'),
    InterestItem(id: 'hiking',           label: 'Hiking/Trail running'),
    InterestItem(id: 'swimming',         label: 'Swimming'),
    InterestItem(id: 'bouldering',       label: 'Bouldering/Indoor climbing'),
    InterestItem(id: 'padel',            label: 'Padel'),
    InterestItem(id: 'pickleball',       label: 'Pickleball'),
    InterestItem(id: 'badminton',        label: 'Badminton'),
    InterestItem(id: 'tennis',           label: 'Tennis'),
    InterestItem(id: 'football_soccer',  label: 'Football/Soccer'),
    InterestItem(id: 'basketball',       label: 'Basketball'),
    InterestItem(id: 'volleyball',       label: 'Volleyball'),
    InterestItem(id: 'martial_arts',     label: 'Martial arts/Boxing'),
    InterestItem(id: 'dance_fitness',    label: 'Dance fitness (Zumba, etc.)'),
    InterestItem(id: 'esports',          label: 'Esports'),
    InterestItem(id: 'cold_plunge',      label: 'Cold plunge/Biohacking'),
    InterestItem(id: 'team_sports',      label: 'Team sports'),
    InterestItem(id: 'skating',          label: 'Skateboarding/Rollerblading'),
    InterestItem(id: 'surfing',          label: 'Surfing/Water sports'),
  ]),
  InterestCategory(id: 'food_drink', title: 'Food & Drink', emoji: '🍜', interests: [
    InterestItem(id: 'food_tourism',      label: 'Food tourism/Local eats'),
    InterestItem(id: 'coffee_culture',    label: 'Coffee culture'),
    InterestItem(id: 'cafe_hopping',      label: 'Café hopping'),
    InterestItem(id: 'cocktails_mixology',label: 'Cocktails/Mocktails & mixology'),
    InterestItem(id: 'wine_tasting',      label: 'Wine tasting'),
    InterestItem(id: 'street_food',       label: 'Street food'),
    InterestItem(id: 'vegan_cooking',     label: 'Vegan/Plant-based cooking'),
    InterestItem(id: 'baking',            label: 'Baking/Pastry'),
    InterestItem(id: 'ramen',             label: 'Ramen/Noodle culture'),
    InterestItem(id: 'sushi',             label: 'Sushi/Japanese cuisine'),
    InterestItem(id: 'meal_prep',         label: 'Meal prepping'),
    InterestItem(id: 'food_photography',  label: 'Food photography'),
  ]),
  InterestCategory(id: 'travel_outdoors', title: 'Travel & Outdoors', emoji: '✈️', interests: [
    InterestItem(id: 'solo_travel',       label: 'Solo travel'),
    InterestItem(id: 'budget_travel',     label: 'Budget travel/Backpacking'),
    InterestItem(id: 'luxury_travel',     label: 'Luxury travel'),
    InterestItem(id: 'van_life',          label: 'Van life/Road trips'),
    InterestItem(id: 'camping',           label: 'Camping/Glamping'),
    InterestItem(id: 'digital_nomad',     label: 'Digital nomad lifestyle'),
    InterestItem(id: 'cultural_tourism',  label: 'Cultural tourism'),
    InterestItem(id: 'city_exploration',  label: 'City exploration/Urban walks'),
    InterestItem(id: 'nature_photography',label: 'Nature photography'),
    InterestItem(id: 'theme_parks',       label: 'Theme parks'),
  ]),
  InterestCategory(id: 'fashion_lifestyle', title: 'Fashion & Lifestyle', emoji: '👗', interests: [
    InterestItem(id: 'thrifting',          label: 'Thrifting/Secondhand shopping'),
    InterestItem(id: 'sustainable_fashion',label: 'Sustainable fashion'),
    InterestItem(id: 'vintage_retro',      label: 'Vintage/Retro styles'),
    InterestItem(id: 'skincare',           label: 'Skincare routines'),
    InterestItem(id: 'streetwear',         label: 'Streetwear'),
    InterestItem(id: 'sneaker_culture',    label: 'Sneaker culture'),
    InterestItem(id: 'minimalism',         label: 'Minimalism'),
    InterestItem(id: 'ootd',               label: 'OOTD/Fashion content'),
    InterestItem(id: 'makeup_beauty',      label: 'Makeup & beauty'),
    InterestItem(id: 'hair_care',          label: 'Hair care/Natural hair'),
    InterestItem(id: 'perfume_fragrance',  label: 'Perfume & fragrance'),
    InterestItem(id: 'interior_design',    label: 'Interior design/Decor'),
    InterestItem(id: 'cottagecore',        label: 'Cottagecore/Aesthetic lifestyle'),
    InterestItem(id: 'dark_fashion',       label: 'Alt/Dark fashion'),
  ]),
  InterestCategory(id: 'finance', title: 'Finance & Money', emoji: '💰', interests: [
    InterestItem(id: 'investing',          label: 'Investing (stocks, ETFs)'),
    InterestItem(id: 'cryptocurrency',     label: 'Cryptocurrency'),
    InterestItem(id: 'side_hustles',       label: 'Side hustles'),
    InterestItem(id: 'entrepreneurship',   label: 'Entrepreneurship'),
    InterestItem(id: 'financial_literacy', label: 'Financial literacy'),
    InterestItem(id: 'budgeting_apps',     label: 'Budgeting apps'),
    InterestItem(id: 'real_estate',        label: 'Real estate investing'),
    InterestItem(id: 'frugal_living',      label: 'Frugal living/FIRE movement'),
    InterestItem(id: 'freelancing',        label: 'Freelancing/Remote work'),
    InterestItem(id: 'passive_income',     label: 'Passive income'),
  ]),
  InterestCategory(id: 'wellness', title: 'Wellness & Mental Health', emoji: '🧘', interests: [
    InterestItem(id: 'mental_health',       label: 'Mental health/Self-care'),
    InterestItem(id: 'therapy_apps',        label: 'Therapy & mental wellness apps'),
    InterestItem(id: 'digital_detox',       label: 'Digital detox'),
    InterestItem(id: 'work_life_balance',   label: 'Work-life balance'),
    InterestItem(id: 'plant_based_diets',   label: 'Plant-based diets'),
    InterestItem(id: 'sleep_optimization',  label: 'Sleep optimization'),
    InterestItem(id: 'breathwork',          label: 'Breathwork/Somatic healing'),
    InterestItem(id: 'astrology',           label: 'Astrology/Birth charts'),
    InterestItem(id: 'spirituality',        label: 'Spirituality/Tarot'),
    InterestItem(id: 'stoicism',            label: 'Stoicism/Philosophy'),
    InterestItem(id: 'adhd_neurodivergent', label: 'ADHD/Neurodivergent life'),
    InterestItem(id: 'gut_health',          label: 'Gut health/Nutrition'),
  ]),
  InterestCategory(id: 'social_causes', title: 'Social Causes', emoji: '🌍', interests: [
    InterestItem(id: 'climate_activism',      label: 'Climate activism'),
    InterestItem(id: 'sustainability',         label: 'Sustainability'),
    InterestItem(id: 'racial_equality',        label: 'Racial equality'),
    InterestItem(id: 'mental_health_awareness',label: 'Mental health awareness'),
    InterestItem(id: 'lgbtq_rights',           label: 'LGBTQ+ rights'),
    InterestItem(id: 'environmental_justice',  label: 'Environmental justice'),
    InterestItem(id: 'ethical_consumerism',    label: 'Ethical consumerism'),
    InterestItem(id: 'animal_rights',          label: 'Animal rights/Veganism'),
    InterestItem(id: 'volunteering',           label: 'Volunteering/Community service'),
    InterestItem(id: 'politics_civics',        label: 'Politics/Civic engagement'),
    InterestItem(id: 'feminism',               label: 'Feminism/Gender equality'),
  ]),
  InterestCategory(id: 'social_community', title: 'Social & Community', emoji: '🤝', interests: [
    InterestItem(id: 'online_communities',   label: 'Online communities/Discord'),
    InterestItem(id: 'language_learning',    label: 'Language learning'),
    InterestItem(id: 'virtual_hangouts',     label: 'Virtual hangouts'),
    InterestItem(id: 'group_chats',          label: 'Group chats'),
    InterestItem(id: 'local_activism',       label: 'Local activism'),
    InterestItem(id: 'pen_pals',             label: 'Pen pals/Letter writing'),
    InterestItem(id: 'book_clubs',           label: 'Book clubs'),
    InterestItem(id: 'running_clubs_social', label: 'Social run clubs'),
    InterestItem(id: 'coworking',            label: 'Coworking/Study-with-me'),
    InterestItem(id: 'substack_writing',     label: 'Newsletter/Substack writing'),
  ]),
  InterestCategory(id: 'education_learning', title: 'Education & Learning', emoji: '📚', interests: [
    InterestItem(id: 'self_improvement', label: 'Self-improvement/Personal growth'),
    InterestItem(id: 'online_courses',   label: 'Online courses (Coursera, Udemy)'),
    InterestItem(id: 'science',          label: 'Science & space'),
    InterestItem(id: 'history',          label: 'History/Geopolitics'),
    InterestItem(id: 'philosophy',       label: 'Philosophy'),
    InterestItem(id: 'psychology',       label: 'Psychology/Human behaviour'),
    InterestItem(id: 'languages',        label: 'Learning languages'),
    InterestItem(id: 'writing',          label: 'Writing/Storytelling'),
    InterestItem(id: 'debates',          label: 'Debates/Intellectual discussions'),
    InterestItem(id: 'trivia',           label: 'Trivia/Quiz nights'),
  ]),
  InterestCategory(id: 'pets_animals', title: 'Pets & Animals', emoji: '🐾', interests: [
    InterestItem(id: 'dogs',             label: 'Dog owner/Dog lover'),
    InterestItem(id: 'cats',             label: 'Cat owner/Cat lover'),
    InterestItem(id: 'exotic_pets',      label: 'Exotic pets'),
    InterestItem(id: 'wildlife',         label: 'Wildlife/Conservation'),
    InterestItem(id: 'pet_photography',  label: 'Pet photography'),
    InterestItem(id: 'aquariums',        label: 'Aquariums/Fish keeping'),
    InterestItem(id: 'birdwatching_pets',label: 'Birdwatching'),
  ]),
];

final List<String> ALL_INTEREST_LABELS =
    INTEREST_CATEGORIES.expand((c) => c.interests.map((i) => i.label)).toList();

final List<String> ALL_PURPOSE_LABELS =
    PURPOSE_OPTIONS.map((p) => p.label).toList();

const List<String> COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Argentina','Armenia',
  'Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados',
  'Belarus','Belgium','Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina',
  'Botswana','Brazil','Brunei','Bulgaria','Burkina Faso','Burundi','Cambodia',
  'Cameroon','Canada','Cape Verde','Central African Republic','Chad','Chile',
  'China','Colombia','Comoros','Congo','Costa Rica','Croatia','Cuba','Cyprus',
  'Czech Republic','Denmark','Djibouti','Dominica','Dominican Republic',
  'East Timor','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea',
  'Estonia','Ethiopia','Fiji','Finland','France','Gabon','Gambia','Georgia',
  'Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau',
  'Guyana','Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran',
  'Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan',
  'Kenya','Kiribati','North Korea','South Korea','Kuwait','Kyrgyzstan','Laos',
  'Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania',
  'Luxembourg','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta',
  'Marshall Islands','Mauritania','Mauritius','Mexico','Micronesia','Moldova',
  'Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia',
  'Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria',
  'Norway','Oman','Pakistan','Palau','Palestine','Panama','Papua New Guinea',
  'Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania',
  'Russia','Rwanda','Saint Kitts and Nevis','Saint Lucia',
  'Saint Vincent and the Grenadines','Samoa','San Marino',
  'Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles',
  'Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
  'South Africa','South Sudan','Spain','Sri Lanka','Sudan','Suriname',
  'Swaziland','Sweden','Switzerland','Syria','Taiwan','Tajikistan','Tanzania',
  'Thailand','Togo','Tonga','Trinidad and Tobago','Tunisia','Turkey',
  'Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates',
  'United Kingdom','United States','Uruguay','Uzbekistan','Vanuatu',
  'Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe',
];
